### ISSUE TITLE
makefile fails to build

### ISSUE THREAD

**Issue by Alexander-Sol** [bmx8177/MS1Connect#2]
Running make results in the following error message

```
g++ -Wall -Werror -std=c++11 -O2 -o bin/createEdge bin/createEdge.cpp
process_begin: CreateProcess(NULL, g++ -Wall -Werror -std=c++11 -O2 -o bin/createEdge bin/createEdge.cpp, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [bin/createEdge] Error 2
```

**Comment by Alexander-Sol** [comment]
I tried substituting relative paths for absolute paths in the make file, but that resulted in the same error message

**Comment by bmx8177** [comment]
That's very weird. Are you using a Windows or Linux system?

Does your make command work on other makefiles not from MS1Connect?

**Comment by Alexander-Sol** [comment]
I'm on Windows 11.

I haven't built any other makefiles, but I'll look for something to test 'make' out on.

**Comment by bmx8177** [comment]
User has general issue with running make files. Issue not specific to this program.
